In [1]:
import numpy as np

In [4]:
funs = dir(np)
i = 0
for fun in funs:
    print(fun, end=" ")
    i += 1
    if i % 5 == 0:
        print()


ALLOW_THREADS AxisError BUFSIZE CLIP ComplexWarning 
DataSource ERR_CALL ERR_DEFAULT ERR_IGNORE ERR_LOG 
ERR_PRINT ERR_RAISE ERR_WARN FLOATING_POINT_SUPPORT FPE_DIVIDEBYZERO 
FPE_INVALID FPE_OVERFLOW FPE_UNDERFLOW False_ Inf 
Infinity MAXDIMS MAY_SHARE_BOUNDS MAY_SHARE_EXACT ModuleDeprecationWarning 
NAN NINF NZERO NaN PINF 
PZERO RAISE RankWarning SHIFT_DIVIDEBYZERO SHIFT_INVALID 
SHIFT_OVERFLOW SHIFT_UNDERFLOW ScalarType Tester TooHardError 
True_ UFUNC_BUFSIZE_DEFAULT UFUNC_PYVALS_NAME VisibleDeprecationWarning WRAP 
_CopyMode _NoValue _UFUNC_API __NUMPY_SETUP__ __all__ 
__builtins__ __cached__ __config__ __deprecated_attrs__ __dir__ 
__doc__ __expired_functions__ __file__ __getattr__ __git_version__ 
__loader__ __name__ __package__ __path__ __spec__ 
__version__ _add_newdoc_ufunc _distributor_init _financial_names _globals 
_mat _pyinstaller_hooks_dir _pytesttester _version abs 
absolute add add_docstring add_newdoc add_newdoc_ufunc 
all allclose alltrue amax amin 
angle any append

# 1 创建数组

## 1.1 使用Python序列创建数组

In [6]:
lst_a  = [1, 2, 3]
arr1 = np.array(lst_a)
print(arr1)
print(type(arr1))

[1 2 3]
<class 'numpy.ndarray'>


In [7]:
dic_a = {
    "name" : "kobayashi",
    "age" : 19,
}

arr2 = np.array(dic_a)
print(arr2)
print(type(arr2))

{'name': 'kobayashi', 'age': 19}
<class 'numpy.ndarray'>


## 2 NumPy 自动生成数组

1. arange 创建顺序数组
2. zeros 创建元素全为 0 的数组
3. ones 创建元素全为 1 的数组
4. eye 创建对角数组
5. random 随机生成数组
6. linspace 生成均匀间隔数组

In [10]:
# arange 函数
arr3 = np.arange(10)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# zeros 函数
arr4 = np.zeros(10)
arr4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
# ones 函数
arr5 = np.ones((2, 3))
arr5

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
# eye 函数
arr6 = np.eye(3)
arr6

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
# random 函数

# 从 [0, 1) 中随机取值
arr7 = np.random.rand(2, 3)
print(arr7)

# 创建指定区间的随机整数数组
arr8 = np.random.randint(1, 10, (2, 3))
print(arr8)

# 创建指定区间的随机浮点数数组
arr9 = np.random.uniform(1, 10, (2, 3))
print(arr9)

[[0.10321568 0.1736428  0.45974213]
 [0.05054859 0.82902975 0.4623709 ]]
[[7 4 9]
 [9 2 1]]
[[1.33663069 4.66050804 9.49445656]
 [6.42288296 2.010427   9.42723744]]


In [24]:
# linspace 函数

# 均匀比例的数组
arr10 = np.linspace(-1, 1, 20)
arr10

array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])

In [27]:
# empty 函数
arr11 = np.empty((2, 3))
arr11

array([[1.33663069, 4.66050804, 9.49445656],
       [6.42288296, 2.010427  , 9.42723744]])

# 2 操作数组的形状和维度

## 1 查看数组的维度与形状

1. 维度个数 ndim
2. 维度大小 shape
3. 打乱数组 random.shuffle

In [30]:
arr = np.arange(20)
np.random.shuffle(arr)
arr

array([ 9, 18, 15,  0,  6, 17,  4, 13, 10,  1,  8,  5,  7,  2, 16, 12, 11,
       14,  3, 19])

## 2 修改数组的维度与形状

1. 修改数组的维度 reshape
2. 翻转数组 transpose | T
3. 展开为一位数组 flatten() | ravel() | reshape()

In [32]:
arr.ndim

1

In [39]:
arr2 = arr.reshape(4, 5)
arr2

array([[ 9, 18, 15,  0,  6],
       [17,  4, 13, 10,  1],
       [ 8,  5,  7,  2, 16],
       [12, 11, 14,  3, 19]])

In [37]:
arr2.transpose()

array([[ 9, 17,  8, 12],
       [18,  4,  5, 11],
       [15, 13,  7, 14],
       [ 0, 10,  2,  3],
       [ 6,  1, 16, 19]])

In [41]:
arr2.flatten()

array([ 9, 18, 15,  0,  6, 17,  4, 13, 10,  1,  8,  5,  7,  2, 16, 12, 11,
       14,  3, 19])

In [44]:
arr2.reshape(1, 20)

array([[ 9, 18, 15,  0,  6, 17,  4, 13, 10,  1,  8,  5,  7,  2, 16, 12,
        11, 14,  3, 19]])

# 3 数组的拼接与分割

## 1 数组拼接

1. 横向拼接 hstack
2. 纵向拼接 vstack

In [46]:
# 横向拼接
arr3 = np.arange(20).reshape(4, 5)
arr3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [48]:
np.hstack((arr2, arr3))

array([[ 9, 18, 15,  0,  6,  0,  1,  2,  3,  4],
       [17,  4, 13, 10,  1,  5,  6,  7,  8,  9],
       [ 8,  5,  7,  2, 16, 10, 11, 12, 13, 14],
       [12, 11, 14,  3, 19, 15, 16, 17, 18, 19]])

In [49]:
np.vstack((arr2, arr3))

array([[ 9, 18, 15,  0,  6],
       [17,  4, 13, 10,  1],
       [ 8,  5,  7,  2, 16],
       [12, 11, 14,  3, 19],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [52]:
# 水平分割
np.hsplit(arr3, 5)

[array([[ 0],
        [ 5],
        [10],
        [15]]),
 array([[ 1],
        [ 6],
        [11],
        [16]]),
 array([[ 2],
        [ 7],
        [12],
        [17]]),
 array([[ 3],
        [ 8],
        [13],
        [18]]),
 array([[ 4],
        [ 9],
        [14],
        [19]])]

In [53]:
np.vsplit(arr2, 2)

[array([[ 9, 18, 15,  0,  6],
        [17,  4, 13, 10,  1]]),
 array([[ 8,  5,  7,  2, 16],
        [12, 11, 14,  3, 19]])]